# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170917_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='option_text',
        ),
    ]
