# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170918_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentuserresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='currentuserresult',
            name='user',
        ),
        migrations.AddField(
            model_name='currentuserresult',
            name='user_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
