# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170918_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuserresult',
            name='results',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='currentuserresult',
            name='right_answers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='right_question',
            field=models.BooleanField(default=False),
        ),
    ]
