# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170919_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuserresult',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='truth',
            field=models.BooleanField(default=False),
        ),
    ]
